### ISSUE TITLE
Some resources not included in last Omnipath version?

### ISSUE THREAD

**Issue by Jordi-Valls** [saezlab/omnipath#11]
Hi all,

I'm new in omnipath and I wanted to know how many resources are included in last version of omnipath (date 22/07/2021). I applied the following command:

import pandas as pd
import igraph as ig
import os
from itertools import permutations
import numpy as np
import omnipath as op

op.interactions.AllInteractions.resources()

And this es the output:

('ABS',
 'ACSN',
 'ACSN_SignaLink3',
 'ARACNe-GTEx_DoRothEA',
 'ARN',
 'Adhesome',
 'AlzPathway',
 'BEL-Large-Corpus_ProtMapper',
 'Baccin2019',
 'BioGRID',
 'BioGRID_ICELLNET',
 'CA1',
 'CancerCellMap',
 'CellChatDB',
 'CellChatDB-cofactors',
 'CellPhoneDB',
 'CellPhoneDB_ICELLNET',
 'CellTalkDB',
 'DEPOD',
 'DIP',
 'DLRP_talklr',
 'DOMINO',
 'DeathDomain',
 'Dinarello2013_ICELLNET',
 'DoRothEA',
 'DoRothEA-reviews_DoRothEA',
 'ELM',
 'EMBRACE',
 'ENCODE-distal',
 'ENCODE-proximal',
 'ENCODE_tf-mirna',
 'FANTOM4_DoRothEA',
 'Fantom5_LRdb',
 'GO-lig-rec_ICELLNET',
 'Guide2Pharma',
 'Guide2Pharma_CellPhoneDB',
 'Guide2Pharma_ICELLNET',
 'Guide2Pharma_LRdb',
 'Guide2Pharma_talklr',
 'HOCOMOCO_DoRothEA',
 'HPMR',
 'HPMR_ICELLNET',
 'HPMR_LRdb',
 'HPMR_talklr',
 'HPRD',
 'HPRD-phos',
 'HPRD_KEA',
 'HPRD_LRdb',
 'HPRD_MIMP',
 'HPRD_talklr',
 'HTRIdb',
 'HTRIdb_DoRothEA',
 'HuRI',
 'I2D_CellPhoneDB',
 'ICELLNET',
 'IMEx_CellPhoneDB',
 'InnateDB',
 'InnateDB-All_CellPhoneDB',
 'InnateDB_CellPhoneDB',
 'InnateDB_ICELLNET',
 'InnateDB_SignaLink3',
 'IntAct',
 'IntAct_CellPhoneDB',
 'IntAct_DoRothEA',
 'JASPAR_DoRothEA',
 'KEA',
 'KEGG-MEDICUS',
 'Kinexus_KEA',
 'Kirouac2010',
 'Kirouac2010_ICELLNET',
 'LMPID',
 'LRdb',
 'Li2012',
 'Lit-BM-17',
 'LncRNADisease',
 'MIMP',
 'MINT_CellPhoneDB',
 'MPPI',
 'Macrophage',
 'Macrophage_ICELLNET',
 'MatrixDB',
 'MatrixDB_CellPhoneDB',
 'NCI-PID_ProtMapper',
 'NFIRegulomeDB_DoRothEA',
 'NRF2ome',
 'NetPath',
 'NetworKIN_KEA',
 'ORegAnno',
 'ORegAnno_DoRothEA',
 'PAZAR',
 'PAZAR_DoRothEA',
 'PhosphoNetworks',
 'PhosphoPoint',
 'PhosphoSite',
 'PhosphoSite_KEA',
 'PhosphoSite_MIMP',
 'PhosphoSite_ProtMapper',
 'PhosphoSite_noref',
 'ProtMapper',
 'REACH_ProtMapper',
 'RLIMS-P_ProtMapper',
 'Ramilowski2015',
 'Ramilowski2015_Baccin2019',
 'Ramilowski2015_ICELLNET',
 'ReMap_DoRothEA',
 'Reactome_ICELLNET',
 'Reactome_LRdb',
 'Reactome_ProtMapper',
 'Reactome_SignaLink3',
 'RegNetwork_DoRothEA',
 'SIGNOR',
 'SIGNOR_ICELLNET',
 'SIGNOR_ProtMapper',
 'SPIKE',
 'SPIKE_ICELLNET',
 'STRING_ICELLNET',
 'STRING_talklr',
 'SignaLink3',
 'SignaLink3_ICELLNET',
 'Sparser_ProtMapper',
 'TCRcuration_SignaLink3',
 'TFactS_DoRothEA',
 'TFe_DoRothEA',
 'TRED_DoRothEA',
 'TRIP',
 'TRRD_DoRothEA',
 'TRRUST_DoRothEA',
 'TransmiR',
 'UniProt_CellPhoneDB',
 'UniProt_LRdb',
 'Wang',
 'Wojtowicz2020',
 'connectomeDB2020',
 'dbPTM',
 'iPTMnet',
 'iTALK',
 'lncrnadb',
 'miR2Disease',
 'miRDeathDB',
 'miRTarBase',
 'miRecords',
 'ncRDeathDB',
 'phosphoELM',
 'phosphoELM_KEA',
 'phosphoELM_MIMP',
 'talklr')
​
Here I cannot see the Vidal HI-III / LIT-13 or HIPPIE from PPI resources for example. There are any problem with those resources??

Thanks!

Jordi

**Comment by deeenes** [comment]
Hi Jordi,

Resources like IntAct, BioGRID, HuRI, etc. are large undirected networks mostly based on Y2H or AP-MS screens. This kind of data is outside of OmniPath's main profile, and we don't intend to provide them in completeness. Only a small fraction of interactions from these databases stay in OmniPath, which meet certain criteria, such as having direction information from another resource, or having multiple references which are not from high-throughput experiments, etc. You can consider their presence as a convenient label that "yes, this interaction was also confirmed by Y2H", but it doesn't make sense to query OmniPath for all IntAct interactions, as that results an arbitrary subset of IntAct.

In addition, OmniPath has a small amount of interactions without direction, but these are only returned by the web service (or the Python client) if you include the `directed=no` parameter in the query.

The databases Vidal HI-III has been replaced by HuRI, and Lit-BM-13 by Lit-BM-17 (these are in the list above). But as I said, only subsets of these are in OmniPath. HIPPIE we don't use at building the network database, it's never been in OmniPath. It can be loaded by `pypath` though. 

Best,

Denes

**Comment by Jordi-Valls** [comment]
Hi Deeenes,

Thanks so much for your quick response. Okay I understand that the major PPI in Omnipath are directed.

Referring to the databases, just to be more clear in the official Omnipath web page at questio "What is OmniPath?" I should clarify these issue that you told me. In addition, I will update the picture were all resources are included with this new names. I ask about HIPPIE because is a new resource included in this picture and I was suprised not find it in these catalog.

Again thanks for your time and quick response.

Jordi

**Comment by deeenes** [comment]
Hi Jordi,

Thanks, these are good points, I will clarify them on the webpage.

Best,

Denes
