### ISSUE TITLE
Interaction annotations by pair, not individual genes

### ISSUE THREAD

**Issue by dnjst** [saezlab/omnipath#16]
Hi, I'm using omnipath to generate lists of gene pairs for cell-cell interaction mapping, and have been trying to create higher-level ontology groupings of interactions, like all TGFB interactions fall into a "TGFB" category. Sources for this would be the "pathway_name" and "annotation" in CellChatDB or "mode" in Connectome.

When it generates the database, Omnipath seems to digest these into 1 gene : 1 pathway annotations, rather than 1 interaction pair : 1 pathway. Almost all of the interactions' categories are determined by the ligand, but apparently not every one.

I tried the latest `pivot_annot` branch and the wide format, and what I get back maps 1 gene : 1 pathway.

```
import omnipath as op
out = op.requests.Annotations.get(
    resources = 'CellChatDB', wide = True)
out.head()

uniprot | genesymbol | entity_type | category | pathway | role
P01137 | TGFB1 | protein | Secreted Signaling | TGFb | ligand
COMPLEX:P36897_P37173 | COMPLEX:TGFBR1_TGFBR2 | complex | Secreted Signaling | TGFb | receptor
P07996 | THBS1 | protein | ECM-Receptor | THBS | ligand
P07996 | THBS1 | protein | Secreted Signaling | TGFb | agonist
P19883 | FST | protein | Secreted Signaling | NODAL | agonist
```

Some interactions are classified in different pathways but have the same ligand or receptor:

An example is:
CD40LG -> CD40 is "Cell-Cell Contact" whereas CD40LG -> ITGA2B_ITGB3 is "Secreted Signaling"
or
ANXA1 -> FPR1 and ANXA1 -> FPR2 are in the "ANNEXIN" pathway, while ANXA1 -> FPR2_LXA4 is just called "ANXA1" pathway.

I also ran:

```
from pypath.inputs.cellchatdb import cellchatdb_download
out = cellchatdb_download()
out['interaction'].sort_values(["ligand","receptor"])


interaction_name | pathway_name | ligand | receptor | agonist | antagonist | co_A_receptor | co_I_receptor | evidence | annotation | interaction_name_2 | rownames
ADCYAP1_ADCYAP1R1 | PACAP | ADCYAP1 | ADCYAP1R1 |   |   |   |   | PMID: 21350482 | Secreted Signaling | ADCYAP1 - ADCYAP1R1 | ADCYAP1_ADCYAP1R1
ADGRE5_CD55 | ADGRE5 | ADGRE5 | CD55 |   |   |   |   | PMID: 11297558 | Cell-Cell Contact | ADGRE5 - CD55 | ADGRE5_CD55
ADIPOQ_ADIPOR1 | ADIPONECTIN | ADIPOQ | ADIPOR1 |   |   |   |   | PMID: 21284979 | Secreted Signaling | ADIPOQ - ADIPOR1 | ADIPOQ_ADIPOR1
ADIPOQ_ADIPOR2 | ADIPONECTIN | ADIPOQ | ADIPOR2 |   |   |   |   | PMID: 21284979 | Secreted Signaling | ADIPOQ - ADIPOR2 | ADIPOQ_ADIPOR2
ADM_CALCR | CALCR | ADM | CALCR |   |   |   |   | KEGG: hsa04080 | Secreted Signaling | ADM - CALCR | ADM_CALCR
```

This is a format which preserves the original database format (each row is an interaction pair), but doesn't yet have the cleaned up gene names, e.g. one of the receptors is `TGFbR1_R2` when omnipath corrects it to something like `COMPLEX:TGFBR1_TGFBR2`.

Is something like what I'm trying to get possible? Am I wrong for wanting to do it in the first place? Thanks for any advice!

**Comment by deeenes** [comment]
Hi,

> Hi, I'm using omnipath to generate lists of gene pairs for cell-cell interaction mapping, and have been trying to create higher-level ontology groupings of interactions, like all TGFB interactions fall into a "TGFB" category. Sources for this would be the "pathway_name" and "annotation" in CellChatDB or "mode" in Connectome.
> 
> When it generates the database, Omnipath seems to digest these into 1 gene : 1 pathway annotations, rather than 1 interaction pair : 1 pathway. Almost all of the interactions' categories are determined by the ligand, but apparently not every one.
> 
> I tried the latest `pivot_annot` branch and the wide format, and what I get back maps 1 gene : 1 pathway.
> 
> ```
> import omnipath as op
> out = op.requests.Annotations.get(
>     resources = 'CellChatDB', wide = True)
> out.head()
> 
> uniprot | genesymbol | entity_type | category | pathway | role
> P01137 | TGFB1 | protein | Secreted Signaling | TGFb | ligand
> COMPLEX:P36897_P37173 | COMPLEX:TGFBR1_TGFBR2 | complex | Secreted Signaling | TGFb | receptor
> P07996 | THBS1 | protein | ECM-Receptor | THBS | ligand
> P07996 | THBS1 | protein | Secreted Signaling | TGFb | agonist
> P19883 | FST | protein | Secreted Signaling | NODAL | agonist
> ```

Indeed, the annotations database annotates genes or their products. Some pathway databases classifies proteins into pathways (e.g. SignaLink), others their interactions (SIGNOR, CellChatDB, NetPath, KEGG). We recently introduced a new optional column `extra_attrs` (extra attributes). This column contains the resource specific interaction annotations such as pathways in a JSON encoded format. You can access it by adding `fields = ['extra_attrs']` to your query. We don't have yet further support in this module for this column, you can process the JSON by the standard Python modules. In the R client we have some functions that can easily extract variables from the column:

```{r}
[ins] r$> ccdb <- import_omnipath_interactions(resources = 'CellChatDB', fields = 'extra_attrs')                                                                                                                                         
[2022-01-31 12:29:11] [SUCCESS] [OmnipathR] Downloaded 1894 interactions.
[ins] r$> ccdb %>% extra_attrs()                                                                                                                                                                                                         
 [1] "SIGNOR_mechanism"      "CellChatDB_category"   "talklr_putative"       "Cellinker_type"        "CellPhoneDB_type"      "Ramilowski2015_source" "SPIKE_effect"          "SPIKE_mechanism"       "CA1_effect"           
[10] "CA1_type"              "ACSN_effect"           "HPRD-phos_mechanism"  
[ins] r$> ccdb %>% extra_attr_values('CellChatDB_category')                                                                                                                                                                              
[1] "Cell-Cell Contact"  "Secreted Signaling" "ECM-Receptor"      
[ins] r$> ccdb %<>% extra_attrs_to_cols('CellChatDB_category')                                                                                                                                                                           
[ins] r$> colnames(ccdb)                                                                                                                                                                                                                 
 [1] "source"                "target"                "source_genesymbol"     "target_genesymbol"     "is_directed"           "is_stimulation"        "is_inhibition"         "consensus_direction"   "consensus_stimulation"
[10] "consensus_inhibition"  "extra_attrs"           "sources"               "references"            "curation_effort"       "n_references"          "n_resources"           "CellChatDB_category"  
[ins] r$> ccdb %>% select(source_genesymbol, target_genesymbol, CellChatDB_category)                                                                                                                                                     
# A tibble: 1,894 × 3
   source_genesymbol target_genesymbol CellChatDB_category
   <chr>             <chr>             <chr>              
 1 JAG2              NOTCH1            Cell-Cell Contact  
 2 DLL1              NOTCH1            Cell-Cell Contact  
 3 IGF1              IGF1R             Secreted Signaling 
 4 JAG1              NOTCH1            Cell-Cell Contact  
 5 WNT5A             FZD2              Secreted Signaling 
 6 EPO               EPOR              Secreted Signaling 
 7 CXCL16            CXCR6             Secreted Signaling 
 8 IGF2              IGF2R             Secreted Signaling 
 9 FLT3LG            FLT3              Secreted Signaling 
10 KITLG             KIT               Secreted Signaling 
# … with 1,884 more rows

```

I see that the CellChatDB pathway is not part of the `extra_attrs` column. I will add it in the upcoming database build.

> 
> Some interactions are classified in different pathways but have the same ligand or receptor:
> 
> An example is: CD40LG -> CD40 is "Cell-Cell Contact" whereas CD40LG -> ITGA2B_ITGB3 is "Secreted Signaling" or ANXA1 -> FPR1 and ANXA1 -> FPR2 are in the "ANNEXIN" pathway, while ANXA1 -> FPR2_LXA4 is just called "ANXA1" pathway.

It's normal that certain genes belong to more than one pathway, this is part of the cross-talk between pathways. Also, the definition of _pathway_ is very different between databases, please take a look which one supports the best your purpose.

> 
> I also ran:
> 
> ```
> from pypath.inputs.cellchatdb import cellchatdb_download
> out = cellchatdb_download()
> out['interaction'].sort_values(["ligand","receptor"])
> 
> 
> interaction_name | pathway_name | ligand | receptor | agonist | antagonist | co_A_receptor | co_I_receptor | evidence | annotation | interaction_name_2 | rownames
> ADCYAP1_ADCYAP1R1 | PACAP | ADCYAP1 | ADCYAP1R1 |   |   |   |   | PMID: 21350482 | Secreted Signaling | ADCYAP1 - ADCYAP1R1 | ADCYAP1_ADCYAP1R1
> ADGRE5_CD55 | ADGRE5 | ADGRE5 | CD55 |   |   |   |   | PMID: 11297558 | Cell-Cell Contact | ADGRE5 - CD55 | ADGRE5_CD55
> ADIPOQ_ADIPOR1 | ADIPONECTIN | ADIPOQ | ADIPOR1 |   |   |   |   | PMID: 21284979 | Secreted Signaling | ADIPOQ - ADIPOR1 | ADIPOQ_ADIPOR1
> ADIPOQ_ADIPOR2 | ADIPONECTIN | ADIPOQ | ADIPOR2 |   |   |   |   | PMID: 21284979 | Secreted Signaling | ADIPOQ - ADIPOR2 | ADIPOQ_ADIPOR2
> ADM_CALCR | CALCR | ADM | CALCR |   |   |   |   | KEGG: hsa04080 | Secreted Signaling | ADM - CALCR | ADM_CALCR
> ```
> 
> This is a format which preserves the original database format (each row is an interaction pair), but doesn't yet have the cleaned up gene names, e.g. one of the receptors is `TGFbR1_R2` when omnipath corrects it to something like `COMPLEX:TGFBR1_TGFBR2`.

You can use the `cellchatdb_interactions` function:

```
>>> from pypath.inputs import cellchatdb
>>> ccdb = cellchatdb.cellchatdb_interactions()
>>> ccdb[:10]
[CellChatDBInteraction(id_a='P01137', id_b=Complex TGFbR1_R2: COMPLEX:P36897_P37173, role_a='ligand', role_b='receptor', effect='unknown', pathway='TGFb', refs=[], category='Secreted Signaling'),
 CellChatDBInteraction(id_a='P07996', id_b='P01137', role_a='agonist', role_b='ligand', effect='stimulation', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='P19883', id_b='P01137', role_a='agonist', role_b='ligand', effect='stimulation', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='P58166', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='P55103', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='O75610', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='O00292', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='Q06828', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='Q14766', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling'),
 CellChatDBInteraction(id_a='P08476', id_b='P01137', role_a='antagonist', role_b='ligand', effect='inhibition', pathway='TGFb', refs=set(), category='Secreted Signaling')]
```

Best,

Denes

**Comment by deeenes** [comment]
For the R package, I created a more detailed tutorial in this topic: https://saezlab.github.io/OmnipathR/articles/extra_attrs.html
