### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by LuckyMD** [saezlab/omnipath#27]
Hey all!

Really cool package (that would benefit from a few example query tutorials ^^). Any plans on putting this on conda-forge? I see the R version is there, but it would be cool to have this on conda as well for us python users who plan to use this in snakemake/nextflow pipelines :).

**Comment by michalk8** [comment]
It already exists, see here: https://anaconda.org/conda-forge/omnipath

**Comment by LuckyMD** [comment]
Thanks @michalk8! My google search only revealed the R version for some reason...
