### ISSUE TITLE
Release current version?

### ISSUE THREAD

**Issue by simonvh** [saezlab/omnipath#28]
Hi, thanks for the great tool! The current version on PyPi results in errors. The latest code on this Github reposistory seems to work fine. Would it be possible to release a new version based on the current source? Thanks!

**Comment by michalk8** [comment]
@deeenes could you please add your PyPI token as `PYPI_PASSWORD` to secrets or give me permissions to add mine?

**Comment by michalk8** [comment]
I was making release previously from my fork, just noticed it doesn't work.

**Comment by michalk8** [comment]
ping @deeenes re https://github.com/saezlab/omnipath/issues/28#issuecomment-1262290981

**Comment by deeenes** [comment]
Hello @michalk8 , sorrry for missing this! Now I made you admin in this repo, and also added a pypi token as you said

**Comment by michalk8** [comment]
Thanks! Closed via 339f684.
