### ISSUE TITLE
RetryError  when run get_resource(‘MSigDB’)

### ISSUE THREAD

**Issue by ChangLu92** [saezlab/omnipath#34]
I got an error when I load the MSigDB data using get_resource(‘MSigDB’)
RetryError: HTTPSConnectionPool(host=‘[omnipathdb.org](http://omnipathdb.org/)’, port=443): Max retries exceeded with url: /annotations?entity_types=protein&format=tsv&resources=MSigDB (Caused by ResponseError(‘too many 500 error responses’))

**Comment by sruthi-hub** [comment]
I get the same error! Did you happen to find a fix? @ChangLu92

**Comment by deeenes** [comment]
Hello, Thanks for reporting and sorry for the inconvenience! Both errors happened due to short service interruptions of our server, these were two independent events 2 weeks apart. It should be working again.
