### ISSUE TITLE
Uniprot IDs to Gene symbols

### ISSUE THREAD

**Issue by Coaasim** [saezlab/omnipath#43]
Hi! 
Is there a way to convert Uniprot IDs into the commonly known gene symbols or names? I would be grateful for any help!

**Comment by deeenes** [comment]
Hi Kasimir, In the OmniPath web service gene symbols are readily available, no need for translation. If you don't have them in the data frame, try to pass `genesymbols = True` to the downloading function.

**Comment by Coaasim** [comment]
Thank you for your fast response! 
I am still not sure how to do that. Unfortunately, I described too imprecisely before what my initial situation is: I have a list of Uniprot IDs from a data set and would like to translate these into gene symbols. In my past attempts via pypath and the UniProt database, I unfortunately also got unusual gene symbols. 
Now I tried to translate the Uniprot IDs with Omnipath using this function and got errors: 
`import omnipath as op
df = op.requests.Annotations.get(proteins = 'A0A087X1C5')`
But this doesn't work. Could you help me? Thank you!

**Comment by deeenes** [comment]
Alright, that's a different problem. If you only want to look up your UniProt IDs in OmniPath data, you can simply use the UniProt IDs. Translation from UniProt to Gene Symbols is not supported yet in this package, but only in pypath: [you can use the `mapping.label` function for that](https://pypath.omnipathdb.org/notebooks/manual.html#Translating-identifiers). And as you mention, you've already tried that. Can you tell me an example of "unusual gene symbols" or any suspected erroneous translation?

**Comment by Coaasim** [comment]
For example this gene symbol HEL-S-133P is not the common known one, it should be LDHA. And there are also other formats like antithrombin/ AT

**Comment by deeenes** [comment]
HEL-S-133P is the primary gene symbol of the TrEMBL record [v9HWB9](https://rest.uniprot.org/uniprotkb/V9HWB9.txt), while LDHA is the primary symbol for the SwissProt record [P00338](https://rest.uniprot.org/uniprotkb/P00338.txt). These are two independent records, despite their sequences being identical, there is no way to make correspondence between them, especially that neither of them have secondary gene symbols. In this case the main question is where did you get v9HWB9 from? Databases and experimental data should use P00338 instead.

```
from pypath.utils import mapping

mapping.map_name('P00338', 'uniprot', 'genesymbol')
{'LDHA'}
mapping.map_name('V9HWB9', 'uniprot', 'genesymbol')
{'HEL-S-133P'}
```

Antithrombin ([P01008](https://rest.uniprot.org/uniprotkb/P01008.txt)) has the primary gene symbol SERPINC1 and it has a secondary symbol too: AT3. These both are translated correctly:

```
from pypath.utils import mapping

mapping.map_name('AT3', 'genesymbol', 'uniprot')
{'P01008'}
mapping.map_name('P01008', 'uniprot', 'genesymbol')
{'SERPINC1'}
mapping.map_name('SERPINC1', 'genesymbol', 'uniprot')
{'P01008'}
```

**Comment by Coaasim** [comment]
Ok. Thank you for looking that up. I will have to look again into the data set that provides the Uniprot IDs.
