### ISSUE TITLE
How to get data on the interactions of all receptor ligands?

### ISSUE THREAD

**Issue by qijt123** [saezlab/omnipath#49]
Hi,

Thank you very much for your Omnipath database.I want to see the information of intercellular communication, so I want to get the data of the interaction of all receptors and ligands in the Omnipath database. How should I do that?

In addition, I also want to know the pathway information of receptor ligand pairs, can this be obtained from the Omnipath?

Thanks.

**Comment by deeenes** [comment]
Answered [here](https://github.com/saezlab/OmnipathR/issues/75).

**Comment by annajbott** [comment]
Can this be done with the python version of omnipath?
