### ISSUE TITLE
Networking issue around package load manifests as a param validation error

### ISSUE THREAD

**Issue by yulicarp** [saezlab/omnipath#50]
When I tried to used this function to retrieve CollecTRI gene regulatory network, for example:
```
collectri = dc.get_collectri(organism='human', split_complexes=False)
collectri
```
It was wrong and the error is here:
```
ValueError: Invalid value `loops` for `InteractionsQuery`. Valid options are: `['database', 'databases', 'dataset', 'datasets', 'directed', 'directeds', 'dorothea_level', 'dorothea_levels', 'dorothea_method', 'dorothea_methods', 'entity_type', 'entity_types', 'field', 'fields', 'format', 'formats', 'genesymbol', 'genesymbols', 'header', 'headers', 'license', 'licenses', 'limit', 'limits', 'organism', 'organisms', 'partner', 'partners', 'password', 'passwords', 'resource', 'resources', 'signed', 'signeds', 'source_target', 'source_targets', 'source', 'sources', 'target', 'targets', 'tfregulons_level', 'tfregulons_levels', 'tfregulons_method', 'tfregulons_methods', 'type', 'types']`.
```

**Comment by deeenes** [comment]
Hi @michalk8,

Apparently, if some of the requests during module load (querying allowed parameter values) fail for whatever reason, the user will experience this `Invalid value 'loops'...` or other similar error. I think we should do two things:

1) make sure we raise a more informative error;
2) if the transaction failed at module load, attempt to populate the allowed values again before evaluating a query (if connection to the server is absolutely not possible, we won't download anything anyway, and should raise an error about that).

Let me know whether you can look at this, or I should try.

**Comment by michalk8** [comment]
I think both options sound good; afaik the issue comes from the fact that on module load, it's not possible to contact the server, so we use pre-defined sets of possible params (which at this point must be out-dated).
Unfortunately, I won't have the capacity to look at this anytime soon :/.
