### ISSUE TITLE
RecursionError: maximum recursion depth exceeded" error when calling interactions.PostTranslational.get()

### ISSUE THREAD

**Issue by olbeimarton** [saezlab/omnipath#6]
Hi,

I have found an error while using the omnipath python client.

`import omnipath as op`
`interactions = op.interactions.PostTranslational.get()`

returns 

`RecursionError: maximum recursion depth exceeded`

Full error message from jupyter notebook:

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-20-69bc68e6b6bc> in <module>
----> 1 interactions = op.interactions.PostTranslational.get()
      2 interactions
      3 #
      4 #RecursionError: maximum recursion depth exceeded

~/miniconda3/lib/python3.7/site-packages/omnipath/_core/requests/_utils.py in wrapper(wrapped, _instance, args, kwargs)
    102     @wrapt.decorator(adapter=wrapt.adapter_factory(argspec_factory))
    103     def wrapper(wrapped, _instance, args, kwargs):
--> 104         return wrapped(*args, **kwargs)
    105 
    106     if hasattr(clazz, "get") and not hasattr(clazz.get, "_wrapped_"):

~/miniconda3/lib/python3.7/site-packages/omnipath/_core/requests/interactions/_interactions.py in get(cls, exclude, **kwargs)
    432         %(get.returns)s
    433         """
--> 434         return cls(exclude=exclude).get(**kwargs)
    435 
    436 

... last 2 frames repeated, from the frame below ...

~/miniconda3/lib/python3.7/site-packages/omnipath/_core/requests/_utils.py in wrapper(wrapped, _instance, args, kwargs)
    102     @wrapt.decorator(adapter=wrapt.adapter_factory(argspec_factory))
    103     def wrapper(wrapped, _instance, args, kwargs):
--> 104         return wrapped(*args, **kwargs)
    105 
    106     if hasattr(clazz, "get") and not hasattr(clazz.get, "_wrapped_"):

RecursionError: maximum recursion depth exceeded

**Comment by michalk8** [comment]
Hi @olbeimarton ,
thanks a lot for spotting this out! It's be fixed in (I've added some tests) https://github.com/saezlab/omnipath/commit/0f7f582d8d522605614a0ac733b6854c901f2c89
and it should already be in PyPI.
